services:
  redis-service:
    image: redis/redis-stack:latest
    container_name: redis-container
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-volume:/data
    restart: unless-stopped

  mysql-service:
    container_name: mysql-container
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis-volume:
  mysql-volume:
    
